// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleExpense.API.DataAccess;

namespace SimpleExpense.API.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    partial class ExpenseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("SimpleExpense.API.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new { ID = 1, Name = "Rent" },
                        new { ID = 2, Name = "Utility" },
                        new { ID = 3, Name = "Groceries" }
                    );
                });

            modelBuilder.Entity("SimpleExpense.API.Models.ExpenseItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Payee");

                    b.HasKey("ID");

                    b.ToTable("Expenses");

                    b.HasData(
                        new { ID = 1, Amount = 23.89m, CategoryID = 3, Date = new DateTime(2018, 7, 23, 0, 0, 0, 0, DateTimeKind.Local), Payee = "Everyday Mart" },
                        new { ID = 2, Amount = 47.50m, CategoryID = 2, Date = new DateTime(2018, 7, 23, 0, 0, 0, 0, DateTimeKind.Local), Payee = "Green Energy" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
